repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']  # needed for !! tags in mkdocs.yml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

# Ruff replaces black, flake8, autoflake and isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.1.14'  # make sure this is always consistent with hatch configs
  hooks:
    - id: ruff
    - id: ruff-format
      args: [--check, --config, ./pyproject.toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.8.0'  # make sure this is always consistent with hatch configs
  hooks:
    - id: mypy
      args: ["--install-types", "--non-interactive"]
      additional_dependencies: [types-tabulate, types-cachetools]

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
