# Project information
site_name: Pytanis
site_description: Utilities for the program organization of conferences using Pretalx!
site_author: Florian Wilhelm
site_url: https://pioneershub.github.io/pytanis/
copyright: 'Copyright &copy; Florian Wilhelm 2023-present'

# Repository
repo_name: PioneersHub/pytanis
repo_url: https://github.com/PioneersHub/pytanis
edit_uri: blob/master/docs

# Navigation
nav:
  - Home:
    - About: index.md
    - Usage:
        - 'Getting Started': usage/installation.md
        - 'Pretalx Client': usage/pretalx.md
        - 'Google Sheets': usage/gsheet.md
        - 'Sending Mails': usage/mail.md
    - Tasks:
        - 'Call for Participation': tasks/cfp.md
        - 'Proposal Review': tasks/review.md
        - 'Talk Selection': tasks/selection.md
        - 'Scheduling': tasks/schedule.md
    - Changelog: changelog.md
    - License: license.md
    - Authors: authors.md
    - Contributing: contributing.md
    # defer to gen-files + literate-nav
    - Reference: reference/pytanis/

# Configuration
docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  favicon: assets/images/favicon.svg
  logo: assets/images/icon.svg
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline # material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb # material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.sections
#    - navigation.expand
#    - navigation.tabs # have additional tabs on top bar
    - navigation.tabs.sticky
    - navigation.instant

watch:
- src/pytanis

# Extensions
plugins:
  # Built-in
  search: {}
  # Extra
  include-markdown: {}
  glightbox: {}
  minify:
    minify_html: true
  mike:
    alias_type: copy
  gen-files:
    scripts:
      - docs/scripts/gen_ref_nav.py
  literate-nav:
    nav_file: SUMMARY.md
  section-index: {}
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
          - src
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_submodules: no
          # Headings
          show_root_heading: true
          show_root_full_path: false
          # Docstrings
          show_if_no_docstring: true
          # Signatures/annotations
          show_signature_annotations: true
          # Other
          show_bases: false

markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: pypa
      repo: hatch
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - "." # !relative $config_dir doesn't work with mike
      auto_append:
        - docs/snippets/links.txt
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FlorianWilhelm/pytanis
#    - icon: fontawesome/solid/blog
#      link: https://....
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/florianwilhelm
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/in/florianwilhelm/
